services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/modelo:/app/modelo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api